2019-11-02 13:22:45,336 ERROR: Exception on /index [GET] [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/routes.py", line 9, in index
    artists = spotify.get_artists()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/spotify.py", line 32, in get_artists
    artists = {'a1' : artists[0], 'a2' : artists[1]}
IndexError: list index out of range
2019-11-02 13:24:48,694 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:27:48,676 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:29:10,139 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:41:14,714 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:41:41,690 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:44:57,165 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:45:44,496 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:47:48,576 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:48:19,177 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:52:58,323 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
2019-11-02 13:58:39,129 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:34]
2019-11-02 14:04:56,888 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:34]
2019-11-02 14:05:46,954 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:34]
2019-11-02 17:11:17,974 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:34]
2019-11-02 17:11:25,840 ERROR: Exception on /index [GET] [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/routes.py", line 9, in index
    artists = database.get_artists()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/database.py", line 24, in get_artists
    results = sp.search(q='artist:' + name, type='artist')
TypeError: must be str, not Artist
2019-11-02 17:11:29,668 ERROR: Exception on /index [GET] [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/routes.py", line 9, in index
    artists = database.get_artists()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/database.py", line 24, in get_artists
    results = sp.search(q='artist:' + name, type='artist')
TypeError: must be str, not Artist
2019-11-02 17:14:27,542 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:34]
2019-11-02 17:14:32,714 ERROR: Exception on /index [GET] [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/routes.py", line 9, in index
    artists = database.get_artists()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/database.py", line 16, in get_artists
    choices = db.session.query(Artist.title.distinct().label('popularity')).limit('2')
AttributeError: type object 'Artist' has no attribute 'title'
2019-11-02 17:14:54,205 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:34]
