2019-11-02 11:34:59,942 ERROR: Exception on /index [GET] [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/routes.py", line 19, in index
    return render_template('index.html', title='Home', artists=artists, correct=correct)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/index.html", line 67, in block "content"
    "{{artists[incorrect]['name']}}")
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: dict object has no element Undefined
2019-11-02 11:35:04,592 ERROR: Exception on /index [GET] [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/routes.py", line 19, in index
    return render_template('index.html', title='Home', artists=artists, correct=correct)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/index.html", line 67, in block "content"
    "{{artists[incorrect]['name']}}")
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: dict object has no element Undefined
2019-11-02 11:35:07,777 ERROR: Exception on /index [GET] [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/routes.py", line 19, in index
    return render_template('index.html', title='Home', artists=artists, correct=correct)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/base.html", line 34, in top-level template code
    {% block content %}
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/templates/index.html", line 67, in block "content"
    "{{artists[incorrect]['name']}}")
  File "/Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/venv/lib/python3.6/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: dict object has no element Undefined
2019-11-02 11:35:55,035 INFO: Popchoose startup [in /Users/gabefoley/Dropbox/Code/Python_Workspace/popchoose/app/__init__.py:31]
